# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 18:02
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0004_auto_20150613_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='ladder',
            name='division',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_round',
            field=models.IntegerField(),
        ),
    ]
