# Generated by Django 3.1.13 on 2021-12-12 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ladder', '0007_auto_20200920_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadderSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateField()),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.ladder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
