# Generated by Django 5.2.5 on 2025-08-13 11:17

import uuid
from django.db import migrations, models


def populate_unique_tokens(apps, schema_editor):
    LadderSubscription = apps.get_model('ladder', 'LadderSubscription')

    # Populate only rows that are still NULL
    for subscription in LadderSubscription.objects.filter(unsubscribe_token__isnull=True).iterator():
        subscription.unsubscribe_token = uuid.uuid4()
        subscription.save(update_fields=['unsubscribe_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0008_laddersubscription'),
    ]

    operations = [
        # Step 1: add nullable, NOT unique
        migrations.AddField(
            model_name='laddersubscription',
            name='unsubscribe_token',
            field=models.UUIDField(null=True, editable=False),
        ),
        # Step 2: backfill unique values
        migrations.RunPython(populate_unique_tokens, migrations.RunPython.noop),
        # Step 3: enforce NOT NULL + unique
        migrations.AlterField(
            model_name='laddersubscription',
            name='unsubscribe_token',
            field=models.UUIDField(null=False, unique=True, editable=False),
        ),
    ]
