# Generated by Django 5.2.5 on 2025-08-13 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0009_laddersubscription_unsubscribe_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laddersubscription',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
