# Generated by Django 5.2.5 on 2025-08-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0010_alter_laddersubscription_unsubscribe_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='If enabled, this season is a draft and not yet published.'),
        ),
    ]
