# Generated by Django 5.2.5 on 2025-08-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0013_prospect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('ready', 'Ready'), ('added', 'Added to draft'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20),
        ),
    ]
