# Generated by Django 5.2.5 on 2025-08-15 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0014_alter_prospect_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftRemoval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_division', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_removals', to='ladder.season')),
            ],
            options={
                'ordering': ('-removed_at',),
                'indexes': [models.Index(fields=['season', 'from_division'], name='ladder_draf_season__045f62_idx')],
            },
        ),
    ]
